import learnkit from '@/data/learnkit.json'
import { CLASSIC_PACKS } from '@/lib/demoData'
import type { Deck } from '@/types'

/** A ready-made deck that can be added from the library. */
export type Pack = {
  id: string
  name: string
  description: string
  source: 'classic' | 'learnkit'
  icon?: string
  /** LearnKit course slug, for grouping. */
  course?: string
  cards: Array<[title: string, content: string]>
}

// Generated by scripts/import-learnkit.mjs from the LearnKit courses.
export const LEARNKIT_PACKS = learnkit as Pack[]

export function allPacks(): Pack[] {
  return [...CLASSIC_PACKS, ...LEARNKIT_PACKS]
}

/** The deck already created from a pack, matched by pack id or (for older data) by name. */
export function deckForPack(decks: Deck[], pack: Pack): Deck | undefined {
  return decks.find((d) => d.packId === pack.id) ?? decks.find((d) => !d.packId && d.name.trim().toLowerCase() === pack.name.toLowerCase())
}

/** LearnKit packs grouped by course, in import order. */
export function learnkitCourses(): Array<{ course: string; title: string; icon: string; packs: Pack[] }> {
  const groups = new Map<string, { course: string; title: string; icon: string; packs: Pack[] }>()
  for (const p of LEARNKIT_PACKS) {
    const key = p.course ?? p.id
    const g = groups.get(key) ?? { course: key, title: p.name.replace(/: (key ideas|terms)$/, ''), icon: p.icon ?? '📘', packs: [] }
    g.packs.push(p)
    groups.set(key, g)
  }
  return [...groups.values()]
}
